# NumPy for AI/ML Engineers

In [3]:
import numpy as np

In [4]:
list = [1, 2, 3, 4, 5]
numpy_array = np.array(list)

print("List:", list)
print("Numpy Array:", numpy_array)

print ("Type of list:", type(list))
print ("Type of numpy array:", type(numpy_array))

List: [1, 2, 3, 4, 5]
Numpy Array: [1 2 3 4 5]
Type of list: <class 'list'>
Type of numpy array: <class 'numpy.ndarray'>


Numpy arrays support element-wise operations, which means that you can perform operations on entire arrays without the need for explicit loops.
This makes Numpy arrays more efficient and faster for numerical computations compared to Python lists. 

In [10]:
array_1 = np.array([10, 20, 30, 40, 50])
array_2 = np.array([10, 10, 10, 10, 10])

print(f"Addition       : {array_1 + array_2}") 
print(f"Subtraction    : {array_1 - array_2}") 
print(f"Multiplication : {array_1 * array_2}")
print(f"Division       : {array_1 / array_2}")

Addition       : [20 30 40 50 60]
Subtraction    : [ 0 10 20 30 40]
Multiplication : [100 200 300 400 500]
Division       : [1. 2. 3. 4. 5.]


In [22]:
array_a = np.array([1, 2, 3])
array_b = np.array([1, 1, 1])

def dot_product(a, b):
    if len(a) != len(b):
        raise ValueError("Arrays must be of the same length")
    return sum(a * b)     

print("Dot Product Result:", dot_product(array_a, array_b))

Dot Product Result: 6


In [ ]:

# 1D arrays. (customer with features)
customer_a = [10, 20, 30]
customer_b = [5, 15, 25]
customer_c = [2, 4, 6]

# 2D array. (customers with features)
customers = np.array([
    [10, 20, 0],
    [5, 15, 25],
    [12, 4, 60]
])


print("Customer Data:\n", customers)

# customers = np.array([customer_a, customer_b, customer_c])

Customer Data:
 [[10 20  0]
 [ 5 15 25]
 [12  4 60]]


Assume we have a 2D NumPy array:

```python
import numpy as np

customers = np.array([
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 28]
])
```

### Printing the Array

```python
print("Customer Data:\n", customers)
```

* Displays the entire 2D array.
* `\n` starts the array on a new line for better readability.

---

### `.shape`

```python
print("Customers shape:", customers.shape)
```

* Returns the dimensions of the array as **(rows, columns)**.
* Example output:

```python
(3, 2)
```

This means:

* **3 rows**
* **2 columns**

---

### `.ndim`

```python
print("Number of dimensions:", customers.ndim)
```

* Returns the number of dimensions (axes) in the array.
* A 2D array has:

```python
2
```

---

### `len()`

```python
print(len(customers))
```

* Returns the number of **rows** in the array.
* Example output:

```python
3
```

> **Note:** `len()` only counts the first dimension (rows). It does **not** return the total number of elements.

---

## Summary

| Function/Attribute | Purpose                          | Example Output         |
| ------------------ | -------------------------------- | ---------------------- |
| `print(customers)` | Displays the entire array        | `[['Alice' '25'] ...]` |
| `customers.shape`  | Returns `(rows, columns)`        | `(3, 2)`               |
| `customers.ndim`   | Returns the number of dimensions | `2`                    |
| `len(customers)`   | Returns the number of rows       | `3`                    |

### Quick Memory Tip

* **`.shape`** → *What is the size?* → `(rows, columns)`
* **`.ndim`** → *How many dimensions?* → `2`
* **`len()`** → *How many rows?* → First dimension only.

This note is a good foundation for learning 2D NumPy arrays before moving on to indexing, slicing, and vectorized operations.


In [28]:
print("Customer Data:\n", customers)
print("Customers shape: ", customers.shape)
print("Number of dimensions: ", customers.ndim)
print("Total elements: ", customers.size)
print("Number of customers: ", len(customers))  # Number of rows
print("Number of features per customer: ", len(customers[0]))  # Number of columns

Customer Data:
 [[10 20  0]
 [ 5 15 25]
 [12  4 60]]
Customers shape:  (3, 3)
Number of dimensions:  2
Total elements:  9
Number of customers:  3
Number of features per customer:  3


## 3D Arrays

In [36]:
array = np.array([
    [
        [1, 3, 5], 
        [7, 9, 11]
    ],
    [
        [2, 4, 6], 
        [8, 10, 12]
    ]
])

# print("3D Array:\n", array)
print("3D Array shape: ", array.shape)
print("3D Array dimensions: ", array.ndim)
print("3D Array size: ", array.size)
print("Number of elements: ", len(array)) 

3D Array shape:  (2, 2, 3)
3D Array dimensions:  3
3D Array size:  12
Number of elements:  2


In [39]:
array = np.array([1, 2])
print("Array data type: ", array.dtype)


array = np.array([1.0, 2.0])
print("Array data type: ", array.dtype)

Array data type:  int64
Array data type:  float64


# Metrix multiplication

In [46]:
A = np.array([
    [1,-2,-6],
    [3,4,-3],
    [3,1,2]
])

B = np.array([
    [1,4,3],
    [0,-2,3],
    [6,1,0]
])

print(f"A.B \n {A@B}")
print("================")
print(f"B.A \n {B@A}")

A.B 
 [[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]
B.A 
 [[ 22  17 -12]
 [  3  -5  12]
 [  9  -8 -39]]


In [52]:
# can use matmul function to calculate matrix multipication
print(f"A.B \n {np.matmul(A,B)}")
print("=================")
print(f"B.A \n {np.matmul(B,A)}")


A.B 
 [[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]
B.A 
 [[ 22  17 -12]
 [  3  -5  12]
 [  9  -8 -39]]


In [ ]:

# .dot function can be used to calculations but not recommonded.

print(f"A.B \n {np.dot(A,B)}")
print("=================")
print(f"B.A \n {np.dot(B,A)}")


A.B 
 [[-35   2  -3]
 [-15   1  21]
 [ 15  12  12]]
B.A 
 [[ 22  17 -12]
 [  3  -5  12]
 [  9  -8 -39]]


## Transpose of a Matrix (Flip)


In [58]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(f"Transpose of A : \n{A.T}")

Transpose of A : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
